name: Build and Push to ECR (Develop)

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: # Add this block
      id-token: write # Grant ID token permission
      contents: read # Grant read permission for the repository content

    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Push Docker Image using Composite Action
        uses: goai-technologies/github-actions-template/build-and-push@main
        with:
          service: swajay-client        # or backend, depending on the repo
          environment: stand-alone
          image_tag: ${{ github.sha }}
          aws-region: ${{ secrets.AWS_REGION }}

  verify-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push   # runs after check-codepipeline
    permissions:
      id-token: write     # needed for OIDC
      contents: read      # needed to checkout the repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check CodeDeploy
        uses: goai-technologies/github-actions-template/check-codeploy@main
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          codedeploy-app-name: stand-alone-swajay-client
          codedeploy-deployment-group: stand-alone-swajay-client-pipeline-dg
